import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from './styles/Home.module.css'
import { useEffect, useState } from "react";
import { useQuery } from '@apollo/client';
import { getJSONIdQuery } from './api/get-data';
import axios from 'axios';
import { DATA_URL } from '../config';
import { useRouter } from 'next/router';






const Home: NextPage = () => {

  const router = useRouter();
  const { tail } = router.query

  const getJSONData = async () => {
    const json_data = await axios.get(DATA_URL);
    setJsonData(json_data.data);
    setIsLoading(false);
  }

  const [loading, setIsLoading] = useState(true);
  const [jsonData, setJsonData] = useState([]);


  const { data: gqlData, loading: gqlLoading, error } = useQuery(getJSONIdQuery, {
    variables: {
      tail: tail
    }
  });

  useEffect(() => {
    getJSONData();
  }, [])


  if (error) {
    console.error(error);
    return null;
  }

  if (gqlLoading || loading) {
    return <h2><a href="#loading" aria-hidden="true" id="loading"><svg aria-hidden="true" height="16" version="1.1" viewBox="0 0 16 16" width="16"><path d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg></a>Loading...</h2>;
  }

  interface element {
    id: number,
    title: string,
    description: string
  }


  if(!gqlData.long_tails[0]){
    return(
      <div>
        No such tail
      </div>
    )
  }

  const displayedElement: element = jsonData[gqlData.long_tails[0].json_id];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         {displayedElement.title} 
         <br/>
         {displayedElement.description} 
      </main>

      
    </div>
  )
}

export default Home
